# Site settings
title: Centre équestre Kaydara
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Centre équestre Kaydara
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kaydara.fr" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
